version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - myapp-network

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - myapp-network

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 2180414
      MYSQL_DATABASE: desplieguemariad
      MYSQL_USER: 2180414
      MYSQL_PASSWORD: 2180414
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - myapp-network

networks:
  myapp-network:
